
### CREAR CATEGORÍA (Requiere ADMIN)
POST http://localhost:8080/api/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJGQUNUT1JfUEFTU1dPUkQiXSwiaWF0IjoxNzYzOTI0Mzg3LCJleHAiOjE3NjM5Mjc5ODd9.mr1ojYR8R9FgrE-M-Xx-geuAr0MQHHs6y-pW5wkFq3Q
{
  "nombre": "Ropa"
}

###  
GET http://localhost:8080/api/categorias

###  
GET http://localhost:8080/api/categorias/buscar?nombre=Electrónicos

### 
GET http://localhost:8080/api/productos/categoria/1

### 
DELETE http://localhost:8080/api/categorias/1
Authorization: Bearer eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJGQUNUT1JfUEFTU1dPUkQiXSwiaWF0IjoxNzYzOTI0Mzg3LCJleHAiOjE3NjM5Mjc5ODd9.mr1ojYR8R9FgrE-M-Xx-geuAr0MQHHs6y-pW5wkFq3Q
